# Intro to Numerical Python

A Python-based version of the "Ch 2 lab" from James et al.'s "Introduction to Statistical Learning" textbook

Based on original notebook: https://nbviewer.jupyter.org/github/emredjan/ISL-python/blob/master/labs/lab_02.3_introduction.ipynb

# What to Do
Try to make sure you can *predict* what a function will do. Build a mental model of NumPy will make you a better programmer and ML engineer.

Ask questions like:

* what should the result's output type be?
* what should the result's *shape* be?
* what should the result's *values* be?

# Outline

* [Data types](#data_types)
* [Dimension and shape](#dimension_and_shape)
* [Reshaping](#reshaping)
* [Elementwise multiplication](#elementwise_multiplication)
* [Matrix multiplication](#matrix_multiplication)
* [Random numbers and random permutations](#prng)
* [Useful functions](#useful_functions)
-- linspace, logspace
-- arange
-- allclose
* [Reductions](#reductions)
-- min
-- max
-- sum
-- prod
* [Indexing](#indexing)


# Key Takeaways

* Numpy array types (`np.array`) have a DIMENSION, a SHAPE, and a DATA-TYPE (dtype)

* * Know what you are using!

* Consider using standard notation to avoid confusion

* * 1-dim arrays of size N could be named `a_N` or `b_N` instead of `a` or `b`

* * 2-dim arrays of size (M,N) could be named `a_MN` instead of `a`

* * With this notation, it is far more clear that `np.dot(a_MN, b_N)` will work, but `np.dot(a_MN.T, b_N)` will not

* Broadcasting is key

* * See https://numpy.org/doc/stable/user/basics.broadcasting.html

* Always use np.array, avoid np.matrix 

* * Why? Array is more flexible (can be 1-dim, 2-dim, 3-dim, 4-dim, and more!)
* * Also, np.matrix will be deprecated soon <https://numpy.org/doc/stable/reference/generated/numpy.matrix.html>

# Further Reading

* Stefan van der Walt, S. Chris Colbert, Gaël Varoquaux. The NumPy array: a structure for efficient numerical computation. Computing in Science and Engineering, Institute of Electrical and Electronics Engineers, 2011. 
<https://hal.inria.fr/inria-00564007/document>

* https://realpython.com/numpy-array-programming/


In [1]:
# import numpy (array library)
import numpy as np


# Basic array creation and manipulation

We use `np.array(...)` function to create arrays

In [2]:
x = np.array([1.0, 6.0, 2.4]);
print(x);

[1.  6.  2.4]


In [3]:
x + 2 # basic element-wise addition

array([3. , 8. , 4.4])

In [4]:
x * 2 # basic element-wise multiplication

array([ 2. , 12. ,  4.8])

In [5]:
x / 2 # basic element-wise division

array([0.5, 3. , 1.2])

In [6]:
x + x # can operate on two arrays of SAME size

array([ 2. , 12. ,  4.8])

In [7]:
x / x # element-wise division

array([1., 1., 1.])

<a id="data_types"></a>

# Data types

Arrays have *data types* (or "dtypes")

In [8]:
y = np.array([1., 4, 3]) # with decimal point in "1.", defaults to 'float' type
print(y)
print(y.dtype)

[1. 4. 3.]
float64


In [9]:
y_int = np.array([1, 4, 3]) # without decimal point, defaults to 'int' type
print(y_int)
print(y_int.dtype)

[1 4 3]
int64


In [10]:
y_float32 = np.array([1, 4, 3], dtype=np.float32) # use optional keyword argument ('kwarg') to specify data type
print(y_float32)
print(y_float32.dtype)

[1. 4. 3.]
float32


In [11]:
y_float64 = np.array([1, 4, 3], dtype=np.float64)

In [12]:
print("y_float32:")
print("  num bytes", y_float32.nbytes) # each entry is 32bits = 4 bytes
print("y_float64:")
print("  num bytes", y_float64.nbytes) # each entry is 64bits = 8 bytes

y_float32:
  num bytes 12
y_float64:
  num bytes 24


In [13]:
z = y_float64 + y_float32 # What happens when you add float32 to float64? *upcast* so no precision is lost
print(z)
print(z.dtype)

[2. 8. 6.]
float64


<a id="dimension_and_shape"></a>

# Dimension and Shape

Arrays have DIMENSION and SHAPE

Dimension (ndim) = an integer value : number of integers needed to index a unique entry of the array

Shape = a tuple of integers : each entry gives the size of the corresponding dimension


In [14]:
y

array([1., 4., 3.])

In [15]:
y.ndim

1

In [16]:
y.shape

(3,)

In [17]:
# Create 2D 3x3 array 'M' as floats
M = np.asarray([[1, 4, 7.0], [2, 5, 8], [3, 6, 9]])
print(M)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [18]:
print(M.ndim)

2


In [19]:
print(M.shape)

(3, 3)


In [20]:
# Create 2D *rectangular* array
M_35 = np.asarray([[1, 4, 7.0, 10, 13], [2, 5, 8, 11, 14], [3, 6, 9, 12, 15]])
print(M_35)

[[ 1.  4.  7. 10. 13.]
 [ 2.  5.  8. 11. 14.]
 [ 3.  6.  9. 12. 15.]]


In [21]:
M_35.shape

(3, 5)

<a id="reshaping"></a>

# Reshaping

Sometimes, we want to transforming from 1-dim to 2-dim arrays

We can either use:
* the *reshape* function
* indexing with the "np.newaxis" built-in <https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis>


#### Demo of reshape

In [22]:
y = np.array([1.0, 4, 3])
print(y)
print(y.shape)

[1. 4. 3.]
(3,)


In [23]:
y_13 = np.reshape(y, (1,3))  # use '_AB' suffix to denote an array with shape (A, B)
print(y_13)
print(y_13.shape)

[[1. 4. 3.]]
(1, 3)


In [24]:
y_31 = np.reshape(y, (3, 1))  # use '_AB' suffix to denote an array with shape (A, B)
print(y_31)
print(y_31.shape)

[[1.]
 [4.]
 [3.]]
(3, 1)


#### Demo of newaxis
Increases dimension of existing array

In [25]:
y = np.array([1.0, 4, 3])
print(y)
print(y.shape)

[1. 4. 3.]
(3,)


In [26]:
y_13 = y[np.newaxis,:]  # use '_AB' suffix to denote an array with shape (A, B)
print(y_13)

[[1. 4. 3.]]


In [27]:
print(y_13.shape)

(1, 3)


In [28]:
y_31 = y[:, np.newaxis]
print(y_31)

[[1.]
 [4.]
 [3.]]


In [29]:
print(y_31.shape)

(3, 1)


In [30]:
y_311 = y[:, np.newaxis, np.newaxis]
print(y_311)

[[[1.]]

 [[4.]]

 [[3.]]]


In [31]:
print(y_311.shape)

(3, 1, 1)


<a id="elementwise_multiplication"></a>

# Elementwise Multiplication

To perform *element-wise* multiplication, use '*' symbol

In [32]:
print(y)

[1. 4. 3.]


In [33]:
print(M)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [34]:
R = M * M
print(R)

[[ 1. 16. 49.]
 [ 4. 25. 64.]
 [ 9. 36. 81.]]


In [35]:
# What happens when we multiply (3,3) shape by a (3,) shape?
# y is implicitly expanded to (1,3) and thus multiplied element-wise to each row

In [36]:
M * y

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [37]:
M * y[np.newaxis,:]  # same thing as above, but more explicit

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [38]:
M * y[:,np.newaxis]  # this makes y multiplied to each column

array([[ 1.,  4.,  7.],
       [ 8., 20., 32.],
       [ 9., 18., 27.]])

In NumPy, multiplying an (M,N) array by an (M,) array is known as *broadcasting*

NumPy's *implicit* rules for what happens are defined here:

https://numpy.org/doc/stable/user/basics.broadcasting.html

y is currently defined as [1. 4. 3.]
M is currently defined as 
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]

In [39]:
# OK, will run, but hard to understand
M * y

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [40]:
# Preferred, make broadcasting explicit
M_33 = M
y_13 = y[np.newaxis,:]
print(y_13)
M_33 * y_13

[[1. 4. 3.]]


array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

<a id="matrix_multiplication"></a>

# Matrix multiplication via np.dot

In NumPy, we can use `np.dot` to perform matrix multiplication.

Docs for `np.dot`: <https://numpy.org/doc/stable/reference/generated/numpy.dot.html>

Keep in mind, the "type" of all the variables here is still NumPy's ND-array. There is no special "matrix" or "vector" type.

In [41]:
M_33

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [106]:
y_3 = np.array([1.0, 4, 3])
print(y_3)
print(y_3.shape)

[1. 4. 3.]
(3,)


## dot of (3,3) and (3,1) arrays

In [110]:
np.dot(M_33, y_3[:,np.newaxis]) # y_3: (3,) -> (3,1)

array([[38.],
       [46.],
       [54.]])

## dot of (3,3) array with itself

In [44]:
np.dot(M_33, M_33)

array([[ 30.,  66., 102.],
       [ 36.,  81., 126.],
       [ 42.,  96., 150.]])

## dot of (3,) array with itself = inner product of that 'vector' with itself

In [ ]:
np.dot(y_3, y_3) # dot product with itself

np.float64(26.0)

In [111]:
np.inner(y_3, y_3)

np.float64(26.0)

In [112]:
np.sum(np.square(y_3)) #another way to write an inner product

np.float64(26.0)

## Verify: dot works even if we 'reshape' y to do (1,3) x (3,1) matrix product

In [48]:
np.dot(y_3[np.newaxis,:], y_3[:,np.newaxis])

array([[26.]])

<a id="pseudorandom_number_generation"></a>

<a id="prng"></a>

# Pseudorandom number generation

### Generate 15 values uniformly distributed between 0 and 1

In [49]:
x = np.random.uniform(size=15) 
print(x)

[0.71793825 0.10770571 0.7169902  0.57723779 0.0384747  0.94551577
 0.39838045 0.32181685 0.35255612 0.66273923 0.80734304 0.13326763
 0.13049517 0.38016436 0.24973444]


### Generate 15 float values normally distributed according to 'standard' normal (mean 0, variance 1)


In [50]:
x = np.random.normal(size=15)
print(x)

[ 0.49646032  2.00218736 -0.21352055 -0.232798    0.7881934   1.10019178
  0.36493531 -1.33897949  0.70796388  1.06875799  0.11633452 -1.79554452
 -0.98265268  1.5926878   0.49236606]


### To make *repeatable* pseudo-randomness, use a generator with the same seed!

A "seed" can just be any *positive* integer. It completely determines how the generator produces its sequence of "random" values

Note: prng is short for pseudo-random number generator, see https://en.wikipedia.org/wiki/Pseudorandom_number_generator

In [51]:
seedA = 9876
seedB = 1234
prng = np.random.RandomState(seedA) 
prng.uniform(size=10)

array([0.1636023 , 0.62062216, 0.90113139, 0.7664971 , 0.51324219,
       0.0966023 , 0.45981236, 0.13687653, 0.94882576, 0.49120575])

In [52]:
prng = np.random.RandomState(seedA)
prng.uniform(size=10)               # should be SAME as above

array([0.1636023 , 0.62062216, 0.90113139, 0.7664971 , 0.51324219,
       0.0966023 , 0.45981236, 0.13687653, 0.94882576, 0.49120575])

In [53]:
prng = np.random.RandomState(seedB)
prng.uniform(size=10)              # should be DIFFERENT than above, bc seed is different

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

### To "shuffle" or permute a sequence, use the permutation function

In [54]:
my_array_5 = np.arange(1,6)

In [55]:
my_array_5

array([1, 2, 3, 4, 5])

In [56]:
prng = np.random.RandomState(8675309)
prng.permutation(my_array_5) # shuffle the sequence

array([3, 5, 4, 1, 2])

In [57]:
prng.permutation(my_array_5) # shuffle it again

array([3, 4, 2, 5, 1])

In [58]:
prng.permutation(my_array_5) # shuffle the sequence again

array([4, 2, 1, 3, 5])

<a id="useful_functions"></a>

# Useful functions

## zeros : Create array of all zeros of desired shape and dtype

In [59]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [61]:
np.zeros((1,2,3), dtype=np.int32)

array([[[0, 0, 0],
        [0, 0, 0]]], dtype=int32)

### ones : Create array of all ones of desired shape and dtype

In [62]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [63]:
np.ones((3,9), dtype=np.int32)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

### linspace : Linearly spaced numbers


In [114]:
x_N = np.linspace(-2, 2, num=5)
print(x_N)


[-2. -1.  0.  1.  2.]


### logspace : Logarithmically spaced numbers

In [117]:
x_N = np.logspace(-2, 2, base=10, num=5)
print(x_N)
for a in x_N:
    print(a)

[1.e-02 1.e-01 1.e+00 1.e+01 1.e+02]
0.01
0.1
1.0
10.0
100.0


### arange : evenly spaced values in given interval

https://numpy.org/doc/stable/reference/generated/numpy.arange.html

Remember, Python counting conventions: 

* start at 0 by default
* the inner bound is *inclusive*
* the upper bound is *exclusive*

In [66]:
# Start at 0 (default), count up by 1 (default) until you get to 4 (exclusive)
x = np.arange(4)
print(x)

[0 1 2 3]


In [67]:
# Start at negative PI, count up by increments of pi/4 until you get to + PI (exclusive)

y = np.arange(start=-np.pi, stop=np.pi, step=np.pi/4)
print(y)

[-3.14159265 -2.35619449 -1.57079633 -0.78539816  0.          0.78539816
  1.57079633  2.35619449]


In [68]:
# Start at negative PI, count up by increments of pi/4 until you get to PI + very small number (exclusive)

y = np.arange(start=-np.pi, stop=np.pi + 0.0000001, step=np.pi/4)
print(y)

[-3.14159265 -2.35619449 -1.57079633 -0.78539816  0.          0.78539816
  1.57079633  2.35619449  3.14159265]


### allclose : verify if all values in an array are "close enough"

https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

Useful when checking if entries in an array are "close enough" to some reference value

E.g. sometimes due to numerical issues of representation, we would consider 5.00002 as good as "5"

In [69]:
x_N = np.arange(4)
print(x_N)

[0 1 2 3]


In [70]:
x2_N = x_N + 0.000001
print(x2_N)

[1.000000e-06 1.000001e+00 2.000001e+00 3.000001e+00]


In [71]:
np.all(x_N == x2_N)

np.False_

In [72]:
np.allclose(x_N, x2_N, atol=0.01) # 'atol' is *absolute tolerance*

True

In [73]:
np.allclose(x_N, x2_N, atol=1e-7) # trying with too small a tolerance will result in False

False

<a id="reductions"></a>

### sort : sort values in *ascending* order

In [74]:
np.sort([3, 4, 5, 1, 2])

array([1, 2, 3, 4, 5])

In [75]:
A_25= np.asarray([
    [3,4,5,1,2],
    [9,7,8,6,0],
])
A_25

array([[3, 4, 5, 1, 2],
       [9, 7, 8, 6, 0]])

Sorting ND arrays requires specifying an axis

In [76]:
np.sort(A_25, axis=0) # sort across first dim (sort each column)

array([[3, 4, 5, 1, 0],
       [9, 7, 8, 6, 2]])

In [77]:
np.sort(A_25, axis=1) # sort across second dim (sort each row)

array([[1, 2, 3, 4, 5],
       [0, 6, 7, 8, 9]])

### argsort : get indices that are usable to sort the array

In [78]:
arr_3 = np.asarray([5.9, 0, 3., -2.1])

In [79]:
ids_3 = np.argsort(arr_3)
ids_3

array([3, 1, 2, 0])

In [80]:
arr_3[ids_3]

array([-2.1,  0. ,  3. ,  5.9])

For ND arrays, you can again provide an `axis` argument

In [81]:
A_25

array([[3, 4, 5, 1, 2],
       [9, 7, 8, 6, 0]])

In [82]:
np.argsort(A_25, axis=0)

array([[0, 0, 0, 0, 1],
       [1, 1, 1, 1, 0]])

In [83]:
np.argsort(A_25, axis=1)

array([[3, 4, 0, 1, 2],
       [4, 3, 1, 2, 0]])

# Reductions


Some numpy functions like '[sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html
)' or 'prod' or 'max' or 'min' that take in many values and produce fewer values.

These kinds of operations are known as "reductions": https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduce.html

Within numpy, any reduction function takes an optional 'axis' kwarg to specify specific dimensions to apply the reduction to


In [84]:
# 2D array creation
A_44 = np.arange(1, 17).reshape(4, 4).transpose()
A_44

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [85]:
np.sum(A_44) # sum of all entries of A

np.int64(136)

In [86]:
np.sum(A_44, axis=0) # sum across dim with index 0 (across rows)

array([10, 26, 42, 58])

In [87]:
np.sum(A_44, axis=1) # sum across dim with index 1 (across cols)

array([28, 32, 36, 40])

In [88]:
np.min(A_44, axis=1) # compute minimum across dim with index 1

array([1, 2, 3, 4])

<a id="indexing"></a>

In [89]:
# 3D arrays now
Q_234 = np.arange(1, 25).reshape((2,3,4))
Q_234

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [90]:
np.min(Q_234, axis=0) # minimum along dim with index 0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
np.min(Q_234, axis=1)

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [92]:
np.min(Q_234, axis=2)

array([[ 1,  5,  9],
       [13, 17, 21]])

# Indexing

Remember Python counts starting at 0

In [93]:
# 2D array creation
A_44 = np.arange(1, 17).reshape(4, 4).transpose()
A_44

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [94]:
# Show the first row
A_44[0]

array([ 1,  5,  9, 13])

In [95]:
# Show the first col
A_44[:, 0]

array([1, 2, 3, 4])

In [96]:
# Grab the second row, third column
A_44[1,2]

np.int64(10)

In [97]:
# Select a range of rows and columns
A_44[0:3, 1:4]

array([[ 5,  9, 13],
       [ 6, 10, 14],
       [ 7, 11, 15]])

In [98]:
# select a range of rows and all columns
A_44[0:2,:]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14]])

In [99]:
# select the *last* row
A_44[-1]

array([ 4,  8, 12, 16])

In [100]:
# select the *second to last* column
A_44[:, -2]

array([ 9, 10, 11, 12])

## Indexing with an iterable of integers

Suppose we want the rows that correspond to ids 1 and 3

The following are all equivalent ways to do that

In [118]:
A_44[[1,3]]

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

In [102]:
row_ids = [1,3]
A_44[row_ids]  # row_ids has type 'list'

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

In [103]:
row_ids = np.asarray([1,3])
A_44[row_ids]  # row_ids has type 'np.ndarray'

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

### The provided list of indices can include multiples and can be unsorted

In [104]:
more_ids = np.asarray([3, 3, 1, 0])
A_44[more_ids]

array([[ 4,  8, 12, 16],
       [ 4,  8, 12, 16],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13]])